// Эмбеддит PLATFORM_MAP → platform-map.embeddings.ts (committed TS-модуль).
// Запуск: NODE_OPTIONS=--dns-result-order=ipv4first npx tsx --conditions=react-server \
//   packages/ai/src/assistant/concierge/embed-map.ts
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { embedQuery } from '../../embeddings';
import { PLATFORM_MAP } from './platform-map';
import type { MapEmbedding, MapEntry } from './types';

function entryText(e: MapEntry): string {
  const parts = [...e.triggers];
  if (e.kind === 'static') parts.push(e.answer);
  return parts.join('\n');
}

async function main() {
  const out: MapEmbedding[] = [];
  for (const e of PLATFORM_MAP) {
    const vec = await embedQuery(entryText(e));
    out.push({ id: e.id, vec });
    console.log(`embedded ${e.id}`);
  }
  const body =
    `// AUTOGENERATED by embed-map.ts — не редактировать вручную.\n` +
    `import type { MapEmbedding } from './types';\n\n` +
    `export const MAP_EMBEDDINGS: MapEmbedding[] = ${JSON.stringify(out)};\n`;
  const path = join(__dirname, 'platform-map.embeddings.ts');
  writeFileSync(path, body);
  console.log(`wrote ${out.length} → ${path}`);
}
main().catch((e) => { console.error(e); process.exit(1); });
